### ISSUE TITLE
I hope VSG can provide editor tools

### ISSUE THREAD

**Issue by JackyLucifer** [vsg-dev/vsgTutorial#1]
Previously, there were editors using OSG, but the supported version was too old

Can you create an editor that displays similar functions

Put the demo directly into the editor

Isn't this version of VSG supported by imgui

I hope to switch between different demos in 3D through interface switching

**Comment by robertosfield** [comment]
I will close this Issue as the online vstgTutorial book isn't the appropriate forum for discussing wider VulkanSceneGraph topics, the right place for this is on the VulkanSceneGraph forum:

https://github.com/vsg-dev/VulkanSceneGraph/discussions

I will answer any questions you have there.
