### ISSUE TITLE
Hello, please release the complete version of the tutorial as soon as possible

### ISSUE THREAD

**Issue by mingkangzh** [vsg-dev/vsgTutorial#3]
I am a beginner and just finished running Hello Word and displayed a teapot model. I think this can achieve the function of displaying robots and point clouds. I have not used OSG before. I need a complete, not necessarily perfect tutorial. I hope you can provide such a tutorial in your spare time. Thank you

**Comment by robertosfield** [comment]
Are you willing to pay for the timely completion of vsgTutorial.  It's taken me 100hrs work so far and I'm 1/3rd the way through, so realistically it's another 200hrs work to complete.  I have to pay the bills to keep food on the table and roof over my head so can't just dedicated full time to activities like vsgTutorial, it takes a lower priority than paying work.

As for robots and point clouds, the VSG is already been used in both these capacities.  If you have questions please use the official Discussion forum:

https://github.com/vsg-dev/VulkanSceneGraph/discussions

**Comment by mingkangzh** [comment]
Thank you very much for your answer. I understand your situation. I will run and analyze other examples to try to understand VSG, and then recommend VSG to a few of my friends. If I encounter problems in the future, I will go to the official discussion forum.
